[package]
name = "rori_irc_entry"
version = "1.0.1"
authors = ["AmarOk <amarok@enconn.fr>"]

[dependencies]
irc = "0.13.4"
rustc-serialize = "*"
regex = "*"
log = "*"
env_logger = "*"
rust-crypto = "^0.2"
openssl = "0.10.4"
