[package]
name = "rori_irc_entry"
version = "0.0.0"
authors = ["AmarOk <amarok@enconn.fr>"]

[dependencies]
irc = { git = "https://github.com/aatxe/irc"}
rustc-serialize = "*"
regex = "*"
log = "*"
env_logger = "*"
openssl = "0.7"
